name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-env

      - name: Check Lint
        run:  uv run just lint-check

  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-env

      - name: Check Formatting
        run:  uv run just format-check

  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: ./.github/actions/setup-env

      - name: Run Tests
        run:  uv run just test-cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
